### ISSUE TITLE
How to add dynamic context

### ISSUE THREAD

**Issue by eyeseast** [tarbell-project/tarbell#171]
Let's say I wanted to build a Tarbell project that, as part of its build process, pulled in posts from a WordPress site using [python-wordpress](https://github.com/eyeseast/python-wordpress).

I'm assuming I could just add a line in `DEFAULT_CONTEXT` like:

```python
DEFAULT_CONTEXT['posts'] = wp.get_recent_posts()
```

Simple enough. Now what if I wanted to get posts for a category, based on something in the URL? Essentially, I think I want to add a custom route to the underlying Flask app.

```python
@site.app.route('/<slug>/')
def category(slug):
    posts = wp.get_category_posts(slug=slug)
    return render_template(posts=posts)
```

I'm just trying out Tarbell, so I'm not sure this is even the right use case. Is there a way to do this? Or am I thinking about this the wrong way?

**Comment by hbillings** [comment]
This seems like it needs to be factored out into more discrete tickets.

**Comment by eads** [comment]
@hbillings you've been assigned to figure out what to do about this one ;)

I think it's just docs at this point -- other tickets cover the issues.

**Comment by eyeseast** [comment]
I can help, too. It's made much easier with the flask-frozen branch, and all I have left to do on that is add docs.

**Comment by eads** [comment]
Yeah! That seems like the best path forward. I added flask-frozen to 1.1
but I'd like to push and either get 1.1 out sooner than end of July or get
this done for 1.0.2.

On Thu, Jul 2, 2015 at 6:26 PM, Chris Amico <notifications@github.com>
wrote:

> I can help, too. It's made much easier with the flask-frozen branch, and
> all I have left to do on that is add docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/171#issuecomment-118184400>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eyeseast** [comment]
Closing this, since it should be solved by Frozen Flask integration and docs. Feel free to reopen if there's something I missed.
