### ISSUE TITLE
Document everything Tarbell does

### ISSUE THREAD

**Issue by eyeseast** [tarbell-project/tarbell#262]
Along the lines of NPR's app template: http://blog.apps.npr.org/2014/07/29/everything-our-app-template-does.html

There are a lot of small but useful bits of functionality I've only found by digging through the source code. Things like authenticating with Google, downloading a spreadsheet, parsing a spreadsheet into context variables and dealing with S3 are pain points that Tarbell solves.

Documenting these would be useful both for getting the most out of Tarbell and for isolating features for development (or if, say, someone wanted to swap out a component). And having all those solved problems clearly explained would be a good selling point.

I could take this on as a way to better familiarize myself with the codebase.

**Comment by hbillings** [comment]
Did we start a doc for this? If so, can someone throw the link in here?

**Comment by eads** [comment]
I feel like this ticket is a little meaningless. can we split it up?

**Comment by eyeseast** [comment]
@eads: Probably. I could at least help out by going through and finding internal or less obvious parts and making a list. I'll work on that.

**Comment by eyeseast** [comment]
If there are no objections, I'm going to close this. I think we've captured enough elsewhere.

**Comment by eads** [comment]
No objections!

On Fri, Apr 1, 2016 at 10:50 AM, Chris Amico <notifications@github.com>
wrote:

> Closed #262 <https://github.com/tarbell-project/tarbell/issues/262>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/262#event-611370413>
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
