### ISSUE TITLE
allow custom TEMPLATE_TYPES

### ISSUE THREAD

**Issue by eads** [tarbell-project/tarbell#264]

**Comment by hbillings** [comment]
So I started looking at tix today and want to get rolling -- could you elaborate a little more on what this means/should look like? I can make inferences from #231, but...

**Comment by eads** [comment]
Basically, it would be nice to have a variable in tarbell_config.py that specified what file types to render using jinja, e.g.:

```
TEMPLATE_TYPES = ['text/css', 'application/javascript']
```

**Comment by hbillings** [comment]
Okay, that's basically what I thought. Thanks!

**Comment by eads** [comment]
the magic should happen in the preview method of the main tarbell app in app.py... I think the legacy code is in fact still kicking around
