### ISSUE TITLE
Call app.preprocess_request in tarbell generate

### ISSUE THREAD

**Issue by eyeseast** [tarbell-project/tarbell#286]
It looks like `tarbell generate` isn't calling `app.preprocess_request()`, which means `current_app` isn't getting attached to the `g` object.

I have a context processor that's doing some data munging on each request, and I'm finding that `g.current_site` is set in preview, but not when building out the static site. Here's my quick fix:

```python
@blueprint.app_context_processor
def process_data():
    # tarbell generate might not be running preprocess_request
    if not g.get('current_site'):
        current_app.preprocess_request()
    # ... rest of the function
```

I can circle back after this project and try to fix this in core. The tricky thing is that `app.preprocess_request` requires a request context, I think.

**Comment by eads** [comment]
Great catch. I can take a look once I'm back from vacation (monday) as well.

On Fri, Jan 2, 2015 at 10:37 PM, Chris Amico <notifications@github.com>
wrote:

> It looks like tarbell generate isn't calling app.preprocess_request(),
> which means current_app isn't getting attached to the g object.
>
> I have a context processor that's doing some data munging on each request,
> and I'm finding that g.current_site is set in preview, but not when
> building out the static site. Here's my quick fix:
>
> @blueprint.app_context_processordef process_data():
>     # tarbell generate might not be running preprocess_request
>     if not g.get('current_site'):
>         current_app.preprocess_request()
>     # ... rest of the function
>
> I can circle back after this project and try to fix this in core. The
> tricky thing is that app.preprocess_request requires a request context, I
> think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/286>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
