### ISSUE TITLE
Using Flask extensions that need app access

### ISSUE THREAD

**Issue by eyeseast** [tarbell-project/tarbell#287]
I have a project (launching soon) that uses [flask-thumbnails](https://github.com/silentsokolov/flask-thumbnails) for resizing images. Like a lot of Flask extensions, it relies on a Flask app for configuration:

```python
from flask.ext.thumbnails import Thumbnail

app = Flask(__name__)

thumb = Thumbnail(app)

app.config['MEDIA_FOLDER'] = '/home/www/media'
app.config['MEDIA_URL'] = '/media/'
```

Which is fine for normal Flask apps, but Tarbell's app is hidden away. Here's how I got around this:

```python
from flask import Blueprint
from flask.ext.thumbnails import Thumbnail

blueprint = Blueprint('project', __name__)
thumbnails = Thumbnail()

@blueprint.record
def app_setup(state):
    "Configure thumbnails"

    # configure thumbnails with the active app
    state.app.config['MEDIA_FOLDER'] = MEDIA_FOLDER
    state.app.config['MEDIA_THUMBNAIL_URL'] = MEDIA_FOLDER
    thumbnails.init_app(state.app)
```

The function decorated with [record](http://flask.pocoo.org/docs/0.10/api/#flask.Blueprint.record) runs when the blueprint gets registered ([here](https://github.com/tarbell-project/tarbell/blob/0.9-beta7/tarbell/app.py#L404)). 

I'm not sure there's a better way to handle this. Maybe a new hook at the end of `TarbellSite.__init__`. Maybe `tarbell_config.py` gets loaded as a config file using `app.config.from_object`. Maybe this is the best way.

**Comment by ghing** [comment]
I had to do something similar:

```
@blueprint.record_once
def add_jina_extensions(state):
    """Register Jinja extensions with the app when this Blueprint is added"""
    state.app.jinja_env.add_extension(OmnitureExtension)
```

I don't think this is a terrible pattern to follow.  I wonder if what's ultimately needed is just a cookbook style documentation section that shares some of these patterns as well as documentation that makes the relationship between Tarbell and Flask more clear.

**Comment by eyeseast** [comment]
+1 on a cookbook. I have recipes to share.

This really might be the simplest pattern. If you're doing something that needs access to the underlying Flask app, `record` or `record_once` is probably the most sane and explicit way to do it, and a little documentation on how to use those functions within Tarbell would probably go a long way towards making Flask extensions more readily available to Tarbell users.

**Comment by eyeseast** [comment]
I can take a run at documenting this, based on how I approached the problem on a couple apps (basically what I outlined above).

**Comment by eads** [comment]
That would be much appreciated.

On Mon, Jul 13, 2015 at 4:34 PM, Chris Amico <notifications@github.com>
wrote:

> I can take a run at documenting this, based on how I approached the
> problem on a couple apps (basically what I outlined above).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/287#issuecomment-121048027>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
