### ISSUE TITLE
Default port issue

### ISSUE THREAD

**Issue by ghost** [tarbell-project/tarbell#288]
I'm setting up a new website with Tarbell and I ran into an issue where serve was forwarding to a troublesome port.

I'm setup with a vagrant machine where my files are hosted on my windows laptop, to avoid issues. The problem cropped up when I went to serve my project. It was defaulting to 127.0.0.1, where I needed 0.0.0.0 to go between my machines.

It would be helpful if you changed the default to the more versatile 0.0.0.0 so others avoid my frustration. And so I don't have to specify the port every time I serve my project.

**Comment by eads** [comment]
This is an interesting issue... the security implications of running on
0.0.0.0 aren't huge, but they're not trivial, either.

You can run `tarbell serve 0.0.0.0:5555` or specify any other IP or port
that you would like.

If we left the defaults as they are and better communicated this option,
would that solve your problem?

On Thu, Jan 29, 2015 at 12:04 PM, Luke Rague <notifications@github.com>
wrote:

> I'm setting up a new website with Tarbell and I ran into an issue where
> serve was forwarding to a troublesome port.
>
> I'm setup with a vagrant machine where my files are hosted on my windows
> laptop, to avoid issues. The problem cropped up when I went to serve my
> project. It was defaulting to 127.0.0.1, where I needed 0.0.0.0 to go
> between my machines.
>
> It would be helpful if you changed the default to the more versatile
> 0.0.0.0 so others avoid my frustration. And so I don't have to specify the
> port every time I serve my project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/288>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by lukerague** [comment]
Yeah, specifying the 0.0.0.0 with serve is how I got it to eventually show in the browser.

It would be nice to not have to remember to do that each time I got to work on my project, but it's not the end of the world if I do have to.

Putting it in the documentation would help others if I'm not a lonely outlier with the setup I'm using. Would it be possible to set the default in the configure file?

**Comment by eads** [comment]
Setting a default in the configure file is a perfect solution. Let's do
that.
