### ISSUE TITLE
`tarbell generate` throws a TypeError

### ISSUE THREAD

**Issue by aboutaaron** [tarbell-project/tarbell#289]
Built a project with the @hbillings template and got this after running `tarbell generate`:

```
Traceback (most recent call last):
  File "/home/aaron/.envs/impact/bin/tarbell", line 9, in <module>
    load_entry_point('tarbell==1.0', 'console_scripts', 'tarbell')()
  File "/home/aaron/.envs/impact/local/lib/python2.7/site-packages/tarbell/cli.py", line 65, in main
    command.__call__(command, args)
  File "/home/aaron/.envs/impact/local/lib/python2.7/site-packages/tarbell/cli.py", line 800, in __call__
    return self.fn(*args, **kw_args)
  File "/home/aaron/.envs/impact/local/lib/python2.7/site-packages/tarbell/cli.py", line 118, in tarbell_generate
    is_folder = os.path.exists(output_root)
  File "/home/aaron/.envs/impact/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, bool found
```

I'm guessing my config is messed up somewhere but I'm not sure. Ideas?

**Comment by aboutaaron** [comment]
This was because I assumed `tarbell generate` was a pre-requisite. Per the docs, you'll only need to do this if you're publishing to somewhere else other than S3. If you're using S3, all you need to run is `tarbell publish`.

**Comment by eads** [comment]
Hmmm this may in fact be a bug -- just out of curiosity does `tarbell
generate /tmp/foo` work? I'm just guessing but maybe it's tripping on a
lack of output path. If that's the case then there should be a sensible
default or at least a message saying the path is required.

On Fri, Feb 27, 2015 at 4:03 PM, Aaron Williams <notifications@github.com>
wrote:

> Closed #289 <https://github.com/tarbell-project/tarbell/issues/289>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/289#event-243555663>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by aboutaaron** [comment]
@eads specifying a path worked, but yes I agree, I think the default should just create a `dist` or `build` directory in the project root. Could this be a worthwhile feature to act as my first contribution?

**Comment by eads** [comment]
That would be an awesome first pull request!

On Fri, Feb 27, 2015 at 6:48 PM, Aaron Williams <notifications@github.com>
wrote:

> Reopened #289 <https://github.com/tarbell-project/tarbell/issues/289>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/289#event-243645558>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eads** [comment]
The directory used should be a default exclude -- or implicitly by using an
underscore prefix.
