### ISSUE TITLE
Missing dateutil and datetime import in app.py

### ISSUE THREAD

**Issue by jywsn** [tarbell-project/tarbell#296]
Going through the tutorial, once I got to the "Displaying data" section using the format_date filter, I got "NameError: global name 'dateutil' is not defined" when trying to preview the page. 

Needed to add this to app.py:

import datetime
import dateutil

**Comment by eads** [comment]
Gak! Great catch. Thanks.

On Mon, Mar 9, 2015 at 12:39 PM, J Wilson <notifications@github.com> wrote:

> Going through the tutorial, once I got to the "Displaying data" section
> using the format_date filter, I got "NameError: global name 'dateutil' is
> not defined" when trying to preview the page.
>
> Needed to add this to app.py:
>
> import datetime
> import dateutil
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/296>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
