### ISSUE TITLE
install-blueprint fails if there is no branch "1.0" in your blueprint

### ISSUE THREAD

**Issue by jmuyskens** [tarbell-project/tarbell#299]
If I understand correctly, the branch of your selected blueprint that Tarbell checks out for you is hardwired to the version of Tarbell. For instance in line 215 of cli.py: `puts(git.checkout(VERSION))` where `VERSION` is the global variable tied to the version of Tarbell, currently `1.0`. 

This means that installing new blueprints using install-blueprint fails if they do not have a branch named '1.0'.

Is this intentional?

**Comment by eads** [comment]
Yes, that's intentional. A bad idea, admittedly.

On Mon, Mar 9, 2015 at 5:44 PM, John Muyskens <notifications@github.com>
wrote:

> If I understand correctly, the branch of your selected blueprint that
> Tarbell checks out for you is hardwired to the version of Tarbell. For
> instance in line 215 of cli.py: puts(git.checkout(VERSION)) where VERSION
> is the global variable tied to the version of Tarbell, currently 1.0.
>
> This means that installing new blueprints using install-blueprint fails if
> they do not have a branch named '1.0'.
>
> Is this intentional?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/299>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eyeseast** [comment]
I started looking into this over the weekend, and it looks like we could remove the code that checks out a specific branch without breaking anything:

In `tarbell_install_blueprint`, [lines 242 and 243](https://github.com/tarbell-project/tarbell/blob/1.0.5/tarbell/cli.py#L242-L243) can go away.

Likewise, in `_newproject`, [lines 578 and 579](https://github.com/tarbell-project/tarbell/blob/1.0.5/tarbell/cli.py#L578-L579) can be removed.

In `tarbell_update`, [lines 486 to 490](https://github.com/tarbell-project/tarbell/blob/1.0.5/tarbell/cli.py#L486-L490) can be updated to pull from whatever branch the blueprint is already on (and should probably also run `git stash pop` to restore local changes).

When installing a blueprint, git will pull from the default branch on Github. If a blueprint currently has a default branch of `1.0`, nothing will change. Tarbell will clone that branch and stay on it; `tarbell update` still works (unless you're detached from `HEAD`, which already breaks things). But a blueprint started from scratch with a default branch called `master` will work, too, without any extra instructions.

As it stands now, the moment we bump Tarbell to version `1.1.0`, we're going to break everyone's blueprints, at least until they switch to branch `1.1`.

If this sounds reasonable, I'll get started on a PR.

**Comment by eads** [comment]
@chrisamico, you are a saint.

I'm very into this fix; it's going to significantly improve everything
going forward.

On Tue, Mar 22, 2016 at 3:41 PM, Chris Amico <notifications@github.com>
wrote:

> I started looking into this over the weekend, and it looks like we could
> remove the code that checks out a specific branch without breaking anything:
>
> In tarbell_install_blueprint, lines 242 and 243
> <https://github.com/tarbell-project/tarbell/blob/1.0.5/tarbell/cli.py#L242-L243>
> can go away.
>
> Likewise, in _newproject, lines 578 and 579
> <https://github.com/tarbell-project/tarbell/blob/1.0.5/tarbell/cli.py#L578-L579>
> can be removed.
>
> In tarbell_update, lines 486 to 490
> <https://github.com/tarbell-project/tarbell/blob/1.0.5/tarbell/cli.py#L486-L490>
> can be updated to pull from whatever branch the blueprint is already on
> (and should probably also run git stash pop to restore local changes).
>
> When installing a blueprint, git will pull from the default branch on
> Github. If a blueprint currently has a default branch of 1.0, nothing
> will change. Tarbell will clone that branch and stay on it; tarbell update
> still works (unless you're detached from HEAD, which already breaks
> things). But a blueprint started from scratch with a default branch called
> master will work, too, without any extra instructions.
>
> As it stands now, the moment we bump Tarbell to version 1.1.0, we're
> going to break everyone's blueprints, at least until they switch to branch
> 1.1.
>
> If this sounds reasonable, I'll get started on a PR.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/299#issuecomment-199982606>
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eyeseast** [comment]
I'll get on it then. Three months without coding (aka family leave) and I have the itch again.
