### ISSUE TITLE
Return response headers other than html?

### ISSUE THREAD

**Issue by jheasly** [tarbell-project/tarbell#301]
Is there a clean/safe/sane way to get at the flask bits so as to be able to return a content type other than html?
`Content-Type text-html; charset=utf-8`

Thanks to `Tarbell`'s flexibility, I've made custom JSON and InDesign Tagged Text/reverse publishing Web responses, only problem is, they don't have the right Content-type/mimetype headers.

For the JSON, I'd like to set: `Content-Type application/json`  
For the InDesign, I'd like to set: `mimetype='text/plain;charset=utf-8'`
`Content-Disposition 'attachment; filename=foo.txt;'`

Any pointers/suggestions greatly appreciated!

Thanks,
John

**Comment by jheasly** [comment]
p.s.: The Tarbell docs say "Need help? File a ticket tagged “support” in Github,"  but the Labels list for me/my login is empty.

**Comment by eyeseast** [comment]
How are you generating the response in the first place? Are you just serving files, or are you using a custom route?

If you're using a custom route to output JSON, make sure you're using [`jsonify`](http://flask.pocoo.org/docs/0.10/api/#flask.json.jsonify) to send the response. That'll set the right mimetype. Assuming you have a blueprint with a custom route, you'd do something like this:

```python
@blueprint.route('/stuff.json')
def stuff():
    data = go_get_data()
    return jsonify(data=data)
```

Or you can set the mimetype by hand:

```python
@blueprint.route('/stuff.json')
def stuff():
    data = go_get_data()
    return json.dumps(data), 200, {'content-type': 'application/json'}
```

Hope that helps.

**Comment by jheasly** [comment]
Was using the plain 'ol file serving. Did not know about custom routes Nifty!  
Since they're in a blueprint, does that mean they have to be created/in place before you create the Tarbell app? Or will they become absorbed into the Flask URL dispatching on restart?  
Many thanks @eyeseast!

**Comment by eyeseast** [comment]
This is on the list of things to be documented. There's more info in #171. Basically, if you define a Flask Blueprint in your `tarbell_config.py` and name it `blueprint`, Tarbell will pick it up and add any routes you define (or template filters, hooks, etc). 

You still have to use a `generate` hook to build out the extra files (again, see discussion in #171). I'm working on some tooling to make that easier.

**Comment by jheasly** [comment]
Ah, I think it all makes sense/all the pieces parts are here. I'll bang away.  
Thanks (again)!

**Comment by jheasly** [comment]
A key bit (from https://github.com/eads/geografiadeldolor/blob/master/tarbell_config.py#L54-L58) from the handy @eyeseast example above:

```Python
from flask import Blueprint

 ...  

blueprint = Blueprint('tarbell_projectname_here', __name__)

 ...  

@blueprint.route('/stuff.json')
def stuff():
    data = go_get_data()
    return json.dumps(data), 200, {'content-type': 'application/json'}
```
