### ISSUE TITLE
Template rendering within a function?

### ISSUE THREAD

**Issue by jheasly** [tarbell-project/tarbell#302]
Just need a little direction here. Okay, so I've got the `mimetype`, and `Content-Disposition` figured out, but I'm not getting how to populate the template variable (`template_data_var` in the example below). Or maybe I'm doing it wrong and it's a `jinja2` operation (rather than `flask`)?

I basically just need to mash together a template (which I've got) and some context to throw to my response; it's the context piece that I don't quite grok ... 

```python
from flask import Blueprint, Response, render_template

 ...  

blueprint = Blueprint('myproject', __name__)

@blueprint.route('/custom/route/')
def my_response():
    the_text = render_template('myproject/print.html', template_data_var=???)
    the_response = Response(the_text, mimetype='application/json')
    the_response.headers['Content-Disposition'] = 'attachment; filename=foo_bar.txt'
    return the_response
```

Thanks for any/all assistance.
— John

**Comment by eads** [comment]
In `render_template` it should be something like:

```
render_template('foo.html', this_var='x', that_var='y')
```

or...

```
context = {
    'this_var': 'x',
    'that_var': 'y',
}
render_template('foo.html', **context)
```

Or do you need access to the default Tarbell context?

**Comment by jheasly** [comment]
(I'm pretty sure) I'd like whatever would be going to the template if I weren't monkeying with the mimetype/header via the custom route ('cause all I want to achieve is the mimetype/header changes).

I think in mycase, it's the name of a Google sheet (and all the iterables that come with it).

Does that make senes? And thank you!

**Comment by eads** [comment]
Absolutely... you can do something like so in your route:

```
context = g.current_site.get_context()
```

See https://github.com/eads/geografiadeldolor/blob/master/tarbell_config.py#L60

**Comment by jheasly** [comment]
That worked great! Thank you!

I ended up with something like this:
```python
from flask import Blueprint, Response, render_template, g

 ...  

blueprint = Blueprint('myproject', __name__)

@blueprint.route('/custom/route/')
def my_response():
    context = g.current_site.get_context()
    the_text = render_template('myproject/print.html', **context)
    the_response = Response(the_text, mimetype='application/json')
    the_response.headers['Content-Disposition'] = 'attachment; filename=foo_bar.txt'
    return the_response
```
And, yeah, I had studying your `geografiadeldolor` (which is a great word) `tarbell_config.py` heavily, so it's nice to know I was getting warm.

Thanks again and have a great weekend.

— John
