### ISSUE TITLE
AttributeError: 'TarbellFileSystemLoader' object has no attribute 'filter_files'

### ISSUE THREAD

**Issue by eyeseast** [tarbell-project/tarbell#304]
Calling [TarbellFileSystemLoader.list_templates](https://github.com/tarbell-project/tarbell/blob/1.0/tarbell/app.py#L90) raises an attribute error. 

This doesn't appear to be affecting anything. Tarbell is still finding and loading templates. It might be that this method is just unnecessary, and we can kill it.

**Comment by eads** [comment]
I did a little research and found `list_templates` is an optional feature of Jinja loaders. Did you need it for something? Otherwise, let's just kill it.

**Comment by eyeseast** [comment]
I think we can just kill it. The only reason I even looked at it as that I was curious what templates it would find. If we do find that it's useful later, we can add it back in.
