### ISSUE TITLE
Tarbell Publish does not Publish. Generate does not Generate

### ISSUE THREAD

**Issue by GrantBlank** [tarbell-project/tarbell#307]
When following the instructions in the tutorial to publish to the Amazon s3 spaces, generate stand alone html, etc., the Terminal returns nothing. Not sure what I am doing wrong.

**Comment by eads** [comment]
need more info :D

On Tue, Apr 14, 2015 at 4:31 PM, GrantBlank <notifications@github.com>
wrote:

> When following the instructions in the tutorial to publish to the Amazon
> s3 spaces, generate stand alone html, etc., the Terminal returns nothing.
> Not sure what I am doing wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/307>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by GrantBlank** [comment]
Ha ha...In the Terminal....I have switched to the project. Ready to publish. Or generate stand alone HTML. I follow the directions in the tutorial as stated....

Generate HTML in a temporary directory:

tarbell generate
Generate HTML in a specific directory:

tarbell generate ~/output/myproject


OR


Publish projects with tarbell publish <target>
If Amazon S3 is configured, you can publish with:

tarbell publish <bucketname>

The Terminal returns a new line with a cursor. That's all. Neither method outputs a final project either locally or in Amazon S3. Does that make sense?

**Comment by eads** [comment]
that's really odd... you're just getting absolutely nothing??

On Tue, Apr 14, 2015 at 5:02 PM, GrantBlank <notifications@github.com>
wrote:

> Ha ha...In the Terminal....I have switched to the project. Ready to
> publish. Or generate stand alone HTML. I follow the directions in the
> tutorial as stated....
>
> Generate HTML in a temporary directory:
>
> tarbell generate
> Generate HTML in a specific directory:
>
> tarbell generate ~/output/myproject
>
> OR
>
> Publish projects with tarbell publish
> If Amazon S3 is configured, you can publish with:
>
> tarbell publish
>
> The Terminal returns a new line with a cursor. That's all. Neither method
> outputs a final project either locally or in Amazon S3. Does that make
> sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/307#issuecomment-93059339>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by GrantBlank** [comment]
Right. Nothing.

**Comment by eads** [comment]
Let's find a time to do a screen share session.

On Wed, Apr 15, 2015 at 4:21 PM, GrantBlank <notifications@github.com>
wrote:

> Right. Nothing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/307#issuecomment-93554677>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by GrantBlank** [comment]
Cool! Maybe Friday?

**Comment by GrantBlank** [comment]
I will email you

**Comment by eads** [comment]
fixed!
