### ISSUE TITLE
TarbellSite.add_site_to_context() doesn't get called during TarbellSite._copy_file()

### ISSUE THREAD

**Issue by ghing** [tarbell-project/tarbell#309]
When I try to run this code in my blueprint:

```
@blueprint.app_context_processor
def default_omniture():
    omniture_conf = g.current_site.project.DEFAULT_CONTEXT.get('OMNITURE', None)
    if omniture_conf is not None:
        return {}

    return {
        'OMNITURE': DEFAULT_OMNITURE,
    }
```

I get this exception:

```
Writing _out/404.html
Traceback (most recent call last):
  File "/Users/ghing/venvs/lead/bin/tarbell", line 9, in <module>
    load_entry_point('tarbell==1.0', 'console_scripts', 'tarbell')()
  File "/Users/ghing/venvs/lead/lib/python2.7/site-packages/tarbell/cli.py", line 65, in main
    command.__call__(command, args)
  File "/Users/ghing/venvs/lead/lib/python2.7/site-packages/tarbell/cli.py", line 800, in __call__
    return self.fn(*args, **kw_args)
  File "/Users/ghing/venvs/lead/lib/python2.7/site-packages/tarbell/cli.py", line 145, in tarbell_generate
    site.generate_static_site(output_root, extra_context)
  File "/Users/ghing/venvs/lead/lib/python2.7/site-packages/tarbell/app.py", line 633, in generate_static_site
    self._copy_file(root.replace(self.blueprint_name, ""), filename, output_root, extra_context)
  File "/Users/ghing/venvs/lead/lib/python2.7/site-packages/tarbell/app.py", line 679, in _copy_file
    preview = self.preview(rel_path, extra_context=extra_context, publish=True)
  File "/Users/ghing/venvs/lead/lib/python2.7/site-packages/tarbell/app.py", line 505, in preview
    rendered = render_template(error_path, **context)
  File "/Users/ghing/venvs/lead/lib/python2.7/site-packages/flask/templating.py", line 126, in render_template
    ctx.app.update_template_context(context)
  File "/Users/ghing/venvs/lead/lib/python2.7/site-packages/flask/app.py", line 716, in update_template_context
    context.update(func())
  File "/Users/ghing/workspace/lead/_blueprint/blueprint.py", line 254, in default_omniture
    omniture_conf = g.current_site.project.DEFAULT_CONTEXT.get('OMNITURE', None)
  File "/Users/ghing/venvs/lead/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'current_site'
```

I'm a bit surprised, because it seems like the call to ` self.app.preprocess_request()` in `TarbellSite._copy_file()` should run `add_site_to_context()` since that method is added with `self.app.before_request(self.add_site_to_context)` in `TarbellSite.__init__()`.

**Comment by eyeseast** [comment]
This is definitely fixed on the `1.0` branch (1ab892996804add54312dd3e568d9643b6ebf17a) but I wonder if it hasn't reached PyPI yet. @eads can you help here?

If you're up for living on the edge, I have a branch that uses Frozen Flask for static site generation that could really use some battle testing: https://github.com/eyeseast/tarbell/tree/frozen-flask (see PR #300). It should solve this and other things, but I'd like to see it work on a site that isn't mine.

**Comment by eads** [comment]
I can roll a release soon! Sorry for being incommunicado, been busy with
life stuff.

On Mon, Apr 20, 2015 at 1:13 PM, Chris Amico <notifications@github.com>
wrote:

> This is definitely fixed on the 1.0 branch (1ab8929
> <https://github.com/tarbell-project/tarbell/commit/1ab892996804add54312dd3e568d9643b6ebf17a>)
> but I wonder if it hasn't reached PyPI yet. @eads
> <https://github.com/eads> can you help here?
>
> If you're up for living on the edge, I have a branch that uses Frozen
> Flask for static site generation that could really use some battle testing:
> https://github.com/eyeseast/tarbell/tree/frozen-flask (see PR #300
> <https://github.com/tarbell-project/tarbell/pull/300>). It should solve
> this and other things, but I'd like to see it work on a site that isn't
> mine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/309#issuecomment-94512356>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by ghing** [comment]
Looks like I'm at straight-up 1.0:

```
__VERSION__ = '1.0'
LONG_VERSION = __VERSION__.replace('b', '-beta')
```

I was looking at the code on GitHub and didn't realize it wasn't in the version on PyPI.

**Comment by eads** [comment]
We need to roll a 1.0.1 post-haste!

On Mon, Apr 20, 2015 at 1:21 PM, Geoffrey Hing <notifications@github.com>
wrote:

> Looks like I'm at straight-up 1.0:
>
> __VERSION__ = '1.0'
> LONG_VERSION = __VERSION__.replace('b', '-beta')
>
> I was looking at the code on GitHub and didn't realize it wasn't in the
> version on PyPI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/309#issuecomment-94514750>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
