### ISSUE TITLE
Integrate flask-frozen

### ISSUE THREAD

**Issue by eads** [tarbell-project/tarbell#311]

**Comment by eyeseast** [comment]
We can close this, right?

**Comment by eads** [comment]
Ah yes indeed

**Comment by eads** [comment]
Curses, I found an backwards compatibility error.

**Comment by hbillings** [comment]
Nonsense, curses are always backward-compatible.

**Comment by eyeseast** [comment]
Everything is broken today. What's the error here?

**Comment by eads** [comment]
It's just a warning, but it prevents the pages from being published. I'm gonna see if there's an easy fix to work around. Otherwise I'll shift 1.0.2 to 1.1, pull in some of the 1.1 tix, and we'll roll 1.1 fairly quickly.

```
$ tarbell publish staging
/Users/davideads/VirtualEnvs/tarbell-py-update/src/tarbell/tarbell/app.py:643: MissingURLGeneratorWarning: Nothing frozen for endpoints geografiadeldolor.espacio. Did you forget an URL generator?
  self.freezer.freeze()
```

**Comment by eyeseast** [comment]
Ah, I think I know what's going on. In that project, you're building pages in the `generate` hook, rather than registering them with `site.freezer.register_generator` or `url_for`, and so Frozen Flask is freaking out because it sees a URL you haven't built.

That is definitely an API change for us (in a positive way, I'd argue, but nevertheless a change). Hopefully using Frozen Flask means you don't have to write this function anymore:

```python
@register_hook('generate')
def create_espacio_pages(site, output_root, quiet=False):
    if not quiet:
        puts("\nCreating espacio pages\n")

    data = site.get_context()
    markers = data["markers"]
    root_path = os.path.join(os.path.realpath(output_root), 'espacio/')

    for marker in markers:
        slug = slughifi(marker["state"].lower())
        page_path = os.path.join(root_path, slug)
        if not os.path.exists(page_path):
            os.makedirs(page_path)
        index_path = os.path.join(page_path, 'index.html')
        if not quiet:
            puts("Writing {0}/espacio/{1}.html".format(output_root, slug))
        with site.app.test_client() as client:
            resp = client.get('/espacio/{0}/'.format(slug))
        f = open(index_path, 'w')
        f.write(resp.data)
        f.close()
```

The question is whether we can (or should) silence that warning to make the old way of generating custom routes still work. If not, then this probably belongs in 1.1.

(Reopening this, since there's clearly still work to do.)

**Comment by eyeseast** [comment]
Here's the relevant line in Frozen Flask: https://github.com/SimonSapin/Frozen-Flask/blob/7d64e34f4133d5d68074e5a3c2eed1447c49aad5/flask_frozen/__init__.py#L243

```python
    def _check_endpoints(self, seen_endpoints):
        """
        Warn if some of the app's enpoints are not in seen_endpoints.
        """
        get_endpoints = set(
            rule.endpoint for rule in self.app.url_map.iter_rules()
            if 'GET' in rule.methods)
        not_generated_endpoints = get_endpoints - seen_endpoints

        if self.static_files_urls in self.url_generators:
            # Special case: do not warn when there is no static file
            not_generated_endpoints -= set(self._static_rules_endpoints())

        if not_generated_endpoints:
            warnings.warn(
                'Nothing frozen for endpoints %s. Did you forget an URL '
                'generator?' % ', '.join(
                    unicode(e) for e in not_generated_endpoints),
                MissingURLGeneratorWarning,
                stacklevel=3)

**Comment by eads** [comment]
I found a fix. The warning is fine, and lets people know they should be doing it the new way. The underlying issue is that the flask-frozen deletes all the stuff in the freeze directory before freezing, which wipes out the files that were being written by the custom code. Tarbell already handles the overwriting an existing generated directory, so it seems entirely safe to tell frozen-flask to not remove any extra files.

**Comment by eads** [comment]
I think with the small fix, we are good to include this in 1.0.2, which I
think I'll wrap in the next few days. I just don't want to break backwards
compatibility without some fanfare.

**Comment by eyeseast** [comment]
I think that's a reasonable fix. It lets people generate files in other ways, if they want, without Tarbell getting in the way.

**Comment by eads** [comment]
It could make sense to remove it down the road, but I think for now it will keep old projects that do generate files in other ways from breaking. And perhaps the flexibility will be useful.
