### ISSUE TITLE
Underscore prefixed sheets aren't ignored

### ISSUE THREAD

**Issue by eyeseast** [tarbell-project/tarbell#323]
The docs say: "Worksheets, columns, and keys names preceded by _ (underscore) are ignored"

But the code says:

```python
def process_xlsx(content):
    """Turn Excel file contents into Tarbell worksheet data"""
    data = {}
    workbook = xlrd.open_workbook(file_contents=content)
    worksheets = workbook.sheet_names()
    for worksheet_name in worksheets:
        worksheet = workbook.sheet_by_name(worksheet_name)

        merged_cells = worksheet.merged_cells
        if len(merged_cells):
            raise MergedCellError(worksheet.name, merged_cells)

        worksheet.name = slughifi(worksheet.name)
        headers = make_headers(worksheet)
        worksheet_data = make_worksheet_data(headers, worksheet)
        data[worksheet.name] = worksheet_data
    return data
```

Should be a pretty easy fix. Just need to actually filter out sheets that start with underscores.

**Comment by eads** [comment]
(facepalm)

Thanks!

On Thu, May 28, 2015 at 4:28 PM, Chris Amico <notifications@github.com>
wrote:

> The docs say: "Worksheets, columns, and keys names preceded by _
> (underscore) are ignored"
>
> But the code says:
>
> def process_xlsx(content):
>     """Turn Excel file contents into Tarbell worksheet data"""
>     data = {}
>     workbook = xlrd.open_workbook(file_contents=content)
>     worksheets = workbook.sheet_names()
>     for worksheet_name in worksheets:
>         worksheet = workbook.sheet_by_name(worksheet_name)
>
>         merged_cells = worksheet.merged_cells
>         if len(merged_cells):
>             raise MergedCellError(worksheet.name, merged_cells)
>
>         worksheet.name = slughifi(worksheet.name)
>         headers = make_headers(worksheet)
>         worksheet_data = make_worksheet_data(headers, worksheet)
>         data[worksheet.name] = worksheet_data
>     return data
>
> Should be a pretty easy fix. Just need to actually filter out sheets that
> start with underscores.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/323>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eyeseast** [comment]
I am determined to find all the bugs and edge cases in this current project. (And I will be so happy when it's finally launched.)
