### ISSUE TITLE
Update the license

### ISSUE THREAD

**Issue by hbillings** [tarbell-project/tarbell#335]
Last updated 2013; copyright Chicago Tribune. Ha.

**Comment by eads** [comment]
Derp. It should retain the Chicago Tribune part though, I believe. We might need to appeal to a Lawyer (TM) to see what see should do here.

**Comment by ryandasher** [comment]
I might know someone who can help here: http://33.media.tumblr.com/5c9d355e6a77e5f73cd64669382e0ee0/tumblr_nkigyv8qZC1qdacjho1_250.gif

**Comment by rnagle** [comment]
![Bird law](http://25.media.tumblr.com/tumblr_lldczeaWn21qbqxsmo1_500.png)

**Comment by eads** [comment]
This shit cray.
