### ISSUE TITLE
fancy error template handling means wrong error bubbles up

### ISSUE THREAD

**Issue by eads** [tarbell-project/tarbell#364]
always a template error, no matter the real underlying error

**Comment by hbillings** [comment]
Ha, I wondered about this. Had a student experience this due to a missing spreadsheet key; took a while to figure out what the heck was going on.

**Comment by eads** [comment]
sorry about that! it's fixed now, we can roll a new minor version soon

On Wed, Aug 26, 2015 at 12:11 PM, Heather Billings <notifications@github.com
> wrote:

> Ha, I wondered about this. Had a student experience this due to a missing
> spreadsheet key; took a while to figure out what the heck was going on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/364#issuecomment-135143069>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by ghing** [comment]
This is driving us crazy over at the Trib.  Would love to see a fix pushed soon,

**Comment by eads** [comment]
Sorry about that. Will publish a new release asap.

On Tue, Sep 15, 2015 at 6:20 PM, Geoffrey Hing <notifications@github.com>
wrote:

> This is driving us crazy over at the Trib. Would love to see a fix pushed
> soon,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/364#issuecomment-140562377>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eads** [comment]
fixed in a4cbcd1f37c9c9ac1a60173d1097e7674b9dd2af
