### ISSUE TITLE
Problem installing Tarbell

### ISSUE THREAD

**Issue by gabehong** [tarbell-project/tarbell#366]
Hi there,

I attempted to install Tarbell through Terminal but it cannot seem to install correctly. I get the following message.
<img width="876" alt="screen shot 2015-08-31 at 6 29 09 pm" src="https://cloud.githubusercontent.com/assets/14035072/9594324/759d12d6-500e-11e5-993c-bd9f13708c57.png">

Thanks for your time

**Comment by eyeseast** [comment]
Hi @gabehong. It looks like you're trying to install it globally, so you'll need to use `sudo` to run the command as the root user.

```bash
sudo pip install tarbell
```

That will give you permission to put files anywhere in the file system.

**Comment by gabehong** [comment]
Thanks Chris!
