### ISSUE TITLE
Buckets with dots not handled by OrdinaryCallingFormat

### ISSUE THREAD

**Issue by hbillings** [tarbell-project/tarbell#368]
I'm unable to `tarbell publish` to a bucket with dots in it, even though I see `s3.py` implements the first fix referenced here: https://github.com/boto/boto/issues/2836

The error I get is `ssl.CertificateError: hostname 'www.anualphonse.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'`

**Comment by eads** [comment]
Are you sure you're on the latest version? I've tested this like crazy.

On Mon, Sep 7, 2015 at 6:26 PM, Heather Billings <notifications@github.com>
wrote:

> I'm unable to tarbell publish to a bucket with dots in it, even though I
> see s3.py implements the first fix referenced here: boto/boto#2836
> <https://github.com/boto/boto/issues/2836>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/368>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by hbillings** [comment]
I'm not sure of anything, Eads. You know that.

**Comment by hbillings** [comment]
Finally got around to this, and, yep, I was running 1.0. Womp womp.

**Comment by eads** [comment]
Your format is anything but ordinary Heather.

On Mon, Oct 5, 2015 at 11:19 AM, Heather Billings <notifications@github.com>
wrote:

> Closed #368 <https://github.com/tarbell-project/tarbell/issues/368>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/368#event-426908231>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
