### ISSUE TITLE
Command to open spreadsheet in browser

### ISSUE THREAD

**Issue by ghing** [tarbell-project/tarbell#371]
It would be really convenient to be able to able to run `tarbell spreadsheet` and have the Google spreadsheet open in my default browser.

I'd also love to be able to run `tarbell browser production` and be able to see the site as deployed in the `production` bucket in my browser.

If these features seem desirable, I'm happy to submit a pull request.

It would be nice to have a way to hook into the tarbell command to be able to add custom management commands, but this seems nontrivial since the tarbell_config.py doesn't get processed until well after the subcommands are wired up.

**Comment by eads** [comment]
YES. I love this idea.

On Fri, Sep 11, 2015 at 2:07 PM, Geoffrey Hing <notifications@github.com>
wrote:

> It would be really convenient to be able to able to run tarbell
> spreadsheet and have the Google spreadsheet open in my default browser.
>
> I'd also love to be able to run tarbell browser production and be able to
> see the site as deployed in the production bucket in my browser.
>
> If these features seem desirable, I'm happy to submit a pull request.
>
> It would be nice to have a way to hook into the tarbell command to be able
> to add custom management commands, but this seems nontrivial since the
> tarbell_config.py doesn't get processed until well after the subcommands
> are wired up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/371>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by eads** [comment]
closed in 583e3159ea6a93509d56813037048133824b2852
