### ISSUE TITLE
Tarbell Tutorial Issue: "No such file or directory error"

### ISSUE THREAD

**Issue by gabehong** [tarbell-project/tarbell#378]
Hi there,

I am trying to complete the Tarbell tutorial. When I answer the question, "Where would you like to create this project?" the automatic answer appears as "Users/gabehong/Projects/tarbell-dev/ethelpayne." 

Under "Users" I actually don't have any folder named Projects, so why is the default answer a link that doesn't exist on my computer? Does this mean that I installed Tarbell incorrectly?

<img width="574" alt="screen shot 2015-10-04 at 5 59 46 pm" src="https://cloud.githubusercontent.com/assets/14035072/10271388/714404c8-6ac2-11e5-8f4b-5a78f6530cc7.png">

Thanks for the help!

**Comment by eads** [comment]
Whoops, something is wrong with your install. Please run `tarbell configure
path` to set the correct directory -- tarbell can create the directories
for ya happily.

On Sun, Oct 4, 2015 at 9:05 PM, gabehong <notifications@github.com> wrote:

> Hi there,
>
> I am trying to complete the Tarbell tutorial. When I answer the question,
> "Where would you like to create this project?" the automatic answer appears
> as "Users/gabehong/Projects/tarbell-dev/ethelpayne."
>
> Under "Users" I actually don't have any folder named Projects, so why is
> the default answer a link that doesn't exist on my computer? Does this mean
> that I installed Tarbell incorrectly?
>
> [image: screen shot 2015-10-04 at 5 59 46 pm]
> <https://cloud.githubusercontent.com/assets/14035072/10271388/714404c8-6ac2-11e5-8f4b-5a78f6530cc7.png>
>
> Thanks for the help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/378>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by gabehong** [comment]
That did the trick. Thanks David!

**Comment by eads** [comment]
Excellent!
