### ISSUE TITLE
Update documentation and screenshots for creating Google client secrets

### ISSUE THREAD

**Issue by ghing** [tarbell-project/tarbell#393]
The docs and screenshots are out of date over at http://tarbell.readthedocs.org/en/1.0.4/install.html.  This part of the process is already a bit confusing.  We should update this so we're not adding to the confusion by having old screenshots and steps.

**Comment by ghing** [comment]
Starting on this now!

**Comment by eads** [comment]
Ha, great minds think alike. I was going to use the blizzard weekend to do
this. I'll tackle the relative path bug instead so we can roll a quick new
release before Miami.

On Fri, Jan 22, 2016 at 11:51 AM, Geoffrey Hing <notifications@github.com>
wrote:

> Starting on this now!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/393#issuecomment-173975220>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by ghing** [comment]
@eads, just made a new PR for this!  Does GitHub automatically notify you of these?

**Comment by ghing** [comment]
Since @eads merged #397, I'm going to go ahead and close this.
