### ISSUE TITLE
`tarbell generate` requires directory argument, docs says it's optional

### ISSUE THREAD

**Issue by jheasly** [tarbell-project/tarbell#398]
In 1.0.4, if you run `tarbell generate` without specifying a directory you get:
```bash
$ tarbell generate

You must specify an output directory (e.g. `tarbell generate _out`)
```
This contradicts [the docs](tarbell.readthedocs.org/en/1.0.4/reference.html#tarbell-generate), which say the output directory's optional.

I think it's a logic issue in `cli.py`.

The 1.0.4 [docs say](tarbell.readthedocs.org/en/1.0.4/reference.html#tarbell-generate) if no directory is supplied, a temporary one will be created, which gets done [here](https://github.com/tarbell-project/tarbell/blob/1.0.4/tarbell/cli.py#L146), based on `output_root` evaluating to `False`.

But if I'm reading the code right, if `output_root` is `False`, you'll never get down to that line as the `else` [here](https://github.com/tarbell-project/tarbell/blob/1.0.4/tarbell/cli.py#L137) traps for `output_root` evaluating to `False`.

**Comment by eyeseast** [comment]
Reopening per discussion on #403. Turns out I missed a page.
