### ISSUE TITLE
Tarbell breaks with oauth2client 2.0.0

### ISSUE THREAD

**Issue by ghing** [tarbell-project/tarbell#400]
It looks like Google released [oauth2client](https://github.com/google/oauth2client/releases) 2.0.0 today.  The previous version was 1.5.2.  

I'm not sure why oauth2client isn't specified as a a dependency since it's used directly in Tarbell.

The problem appears to be that `keyring_storage` is now in `oauth2client.contrib.keyring_storage` (https://github.com/google/oauth2client/blob/6531263b7ed73de23d56562fa2d86c12e3b264c7/oauth2client/contrib/keyring_storage.py).

A stack trace from `tarbell configure` called with the offending version of oauth2client looks like this:

```
Traceback (most recent call last):
  File "/usr/local/bin/tarbell", line 7, in <module>
    from tarbell.cli import main
  File "/usr/local/lib/python2.7/site-packages/tarbell/cli.py", line 41, in <module>
    from .app import pprint_lines, process_xlsx, copy_global_values
  File "/usr/local/lib/python2.7/site-packages/tarbell/app.py", line 33, in <module>
    from .oauth import get_drive_api
  File "/usr/local/lib/python2.7/site-packages/tarbell/oauth.py", line 9, in <module>
    from oauth2client import keyring_storage
ImportError: cannot import name keyring_storage
```

Workaround is this:

    pip uninstall oauth2client
    pip install oauth2client==1.5.2

Permanent fix would be either to specify 1.5.2 in the dependencies, or import like this:

```
try:
   from oauth2client.contrib import keyring_storage
except ImportError:
   from oauth2client import keyring_storage
```

**Comment by ghing** [comment]
@eads I can do the work to fix this, but I need some background about why oauth2client isn't listed in the dependencies in setup.py.

**Comment by eads** [comment]
oooh dammit. oauth2client is a dependency of the another library (the
python google api one, not close to a place where I can easily look it up).
So it's possible it specifies a greater-than style version string which
would cause things to break.

On Tue, Feb 16, 2016 at 4:16 PM, Geoffrey Hing <notifications@github.com>
wrote:

> @eads <https://github.com/eads> I can do the work to fix this, but I need
> some background about why oauth2client isn't listed in the dependencies in
> setup.py.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/400#issuecomment-184877908>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by stucka** [comment]
Yeah, I saw a dependency for >= 1.3 , but no maximum version.

It had been working with 1.4.2 on @gurmanbh 's machine. Worked again:
pip install oauth2client==1.4.2

**Comment by eads** [comment]
I'm going to try and roll a new tarbell version this week to address this
issue among others.

On Fri, Feb 19, 2016 at 4:25 PM, Mike Stucka <notifications@github.com>
wrote:

> Yeah, I saw a dependency for >= 1.3 , but no maximum version.
>
> It had been working with 1.4.2 on @gurmanbh <https://github.com/gurmanbh>
> 's machine. Worked again:
> pip install oauth2client==1.4.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarbell-project/tarbell/issues/400#issuecomment-186413074>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
