### ISSUE TITLE
Let master be master

### ISSUE THREAD

**Issue by eyeseast** [tarbell-project/tarbell#402]
Coming back after a bunch of time away (baby!) and finding it really hard to figure out where things stand, in part because the most current branch is, I think, `1.0.5`. We've had this problem before where a pull request targets a release, then a release happens before that pull gets merged, and then commits get lost in the shuffle.

Is there a downside to making master the real master branch, and using tags to mark releases?

**Comment by eads** [comment]
Yes there is, sadly, because of the branch dependency of blueprints. I
think that's the absolute #1 top priority to solve these days. Because
master should be master.
