### ISSUE TITLE
New project grabs old version of google sheet

### ISSUE THREAD

**Issue by jonathonberlin** [tarbell-project/tarbell#446]
Hello,

When I create a new project and run through steps, everything appears good except I seem to be pulling in an old branch of our google sheet template. It's one generation old, missing a few tabs.

Where in the set-up is the relationship with the the template Tarbell inserts into the sheet and how can I change it to the correct branch?

tx,

Jonathon

**Comment by eyeseast** [comment]
Check the `SPREADSHEET_KEY` setting in `tarbell_config.py` in your project. It should match the key of your new sheet.

**Comment by jonathonberlin** [comment]
Thanks Chris!

I checked the key and that seems to be lined up. The way we have our blueprint built we put a spreadsheet template into the project's google sheet. that sheet has the fields we use to import into our cms.

That "template" sheet is what is outdated for me. Somehow I'm grabbing an old "template" when I create a new project.

Jonathon

**Comment by eyeseast** [comment]
Ah, I get what you're saying now. Check what branch your `_blueprint` directory is on. Tarbell clones it as a submodule, and older versions of Tarbell would try to switch to a branch matching Tarbell's major version (probably `1.0`). If you `cd _blueprint` and run `git status`, that'll at least tell you if you're on an old branch, or maybe pinned to a commit. Assuming you're making changes on `master`, you can do `git checkout master` (from within the `_blueprint directory`) and get the right version.

See if that helps.

**Comment by jonathonberlin** [comment]
Thank you both!

**Comment by jonathonberlin** [comment]
I compared the spreadsheets in both branches ``1.0`` and ``master``, and the ``1.0`` branch had the version of the spreadsheet I was looking for. I had the correct repository url in the ``settings.yaml`` but I'm not sure how to determine what branch of that repository is accessed when I create a new project. (I should say that my tarbell accesses the ``master`` branch if I were to judge by the spreadsheet issue -- what I mean is I don't know why that is or where in the process that relationship is determined)

As a workaround, I put the desired version of the ``_spreadsheet.xlsx`` in the ``master`` and committed that to the repo. Now I get the correct spreadsheet version when I create a new project, but it's possible that I may be missing other changes and just fixed one thing.

Curious: why does it matter which version of tarbell I am running and how can I make sure I'm using the right version for this issue?

Thanks again!!!

**Comment by eyeseast** [comment]
The latest version --  `1.0.7` -- will clone your blueprint on whatever you set as your default branch on Github. Before `1.0.5`, Tarbell would clone the blueprint, then try to checkout its `1.0` branch (matching Tarbell's major version). This was a pain and led to lots of bugs.

The easiest fix, I think, is upgrading your global Tarbell install (`sudo pip install tarbell` from **outside** any active virtualenv). And then look at your blueprints on Github and make sure the default branch is `master` (or whatever you're committing to).
