### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by miguelpaz** [tarbell-project/tarbell#453]
I am on Python 2.7.10 on MacOS El Capitan:
When I install via pip and via sudo pip... I get an error related to six 1.4.1. Any recommendations?

> Found existing installation: six 1.4.1
>     DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
>     Uninstalling six-1.4.1:
> Exception:
> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
>     prefix=options.prefix_path,
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
>     requirement.uninstall(auto_confirm=True)
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
>     paths_to_remove.remove(auto_confirm)
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
>     renames(path, new_path)
>   File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
>     shutil.move(old, new)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
>     copy2(src, real_dst)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
>     copystat(src, dst)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
>     os.chflags(dst, st.st_flags)
> OSError: [Errno 1] Operation not permitted: '/tmp/pip-8jnHLK-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by eyeseast** [comment]
I ran into this just now. It's a Python issue, separate from Tarbell, but still super annoying. The way I got around it -- and this is more annoying -- is to install Python from scratch instead of using the semi-broken version that ships with OSX, and then start setting up my python environment.

**Comment by miguelpaz** [comment]
I figured it could be that @eyeseast. Annoying. Will take a stab at it.
